[package]
name = "rebo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rebo"
crate-type = ["cdylib"]

[dependencies]
nix = { version = "0.29.0", features = ["reboot"] }
pyo3 = "0.21.1"
